### ISSUE TITLE
Wrong url in wiki

### ISSUE THREAD

**Issue by larmar** [mabazyar/Open-vSwitch-on-Centos7#1]
Url seems changed

http://downloads.naulinux.ru/pub/NauLinux/Extras/7x/RPMS/Projects/OpenFlow/python-openvswitch-2.5.0-2.el7.noarch.rpm

**Comment by mabazyar** [comment]
Thanks for the comment.
The source link (non-rpm one) was provided in the doc, which was the lastest one at the time of writing.
The link is still functioning.
Thanks,

**Comment by mabazyar** [comment]
Closing the issue because of lack of activity.
